### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by RSNY** [deepakshrma/node-behance-api#1]
Hello!
I have installed NodeJS to my Debian Server but can't get Behance module to install:

npm ERR! error installing node-behance-api@1.2.0
npm ERR! Error: No compatible version found: request@'^2.45.0'

**Comment by RSNY** [comment]
Sorry false start! Update nodejs and npm to latest versions, seems working!

**Comment by deepakshrma** [comment]
Thanks. Kindly report if you find anything creepy in it.
