### ISSUE TITLE
Cannot find module 

### ISSUE THREAD

**Issue by implict** [deepakshrma/node-behance-api#2]
Hi,
I got a issue as below.

_Cannot find module '/node_modules/node-behance-api/lib/options.json'_

How to resolve this?

**Comment by deepakshrma** [comment]
Will you provide sample code? How you are using it ? which api you are testing ?
kindly follow the given code snippet from blog
http://www.tothenew.com/blog/adobe-behance-portfolio-development-apis-node-behance-api/
if still problem, let me know.

**Comment by implict** [comment]
I got an error message as below.
_Uncaught Error: Cannot find module '/node_modules/node-behance-api/lib/options.json'_

**Comment by deepakshrma** [comment]
Can you share the updated code that you are using? and you package.json
