### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by bearjr** [deepakshrma/node-behance-api#3]
ReferenceError
__dirname is not defined
new exports.ConfigManager
https://r7wrmw50lp.codesandbox.io/node_modules/node-behance-api/lib/helpers.js:10:40
Function.Behance.initOptions
https://r7wrmw50lp.codesandbox.io/node_modules/node-behance-api/behance.js:21:5

This is my error message and I don't know what I'am doing wrong, can you help me?

**Comment by deepakshrma** [comment]
can you give me more info about enviroment
Node version, Module version.
I tested in my local, it is working fine.
Just released a version. You can try with latest 1.3.0
